const state={articles:[],filtered:[],page:1,pageSize:20};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const outletClassMap={
  'Associated Press':'outlet-ap',
  'BBC News':'outlet-bbc',
  'Bloomberg':'outlet-bloomberg',
  'CNBC':'outlet-cnbc',
  'CNN Business':'outlet-cnn',
  'The New York Times':'outlet-nyt',
  'Reuters':'outlet-reuters',
  'The Guardian':'outlet-guardian',
  'The Daily Telegraph':'outlet-telegraph',
  'The Wall Street Journal':'outlet-wsj'
};
function outletClass(name){return outletClassMap[name]||'outlet-default'}
function parseDate(raw){if(!raw)return null;let s=raw.replace(/^(published|updated)\s*:?\s*/i,'').replace(/—.*$/,'').trim();const d=new Date(s);return isNaN(d)?null:d}
function displayDate(raw){const d=parseDate(raw);return d?new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric'}).format(d):raw||'Date not recorded'}
function init(data,summary){state.articles=data;state.filtered=data;$('#recordCount').textContent=data.length.toLocaleString();const outlets=[...new Set(data.map(x=>x.outlet))];$('#outletSelect').insertAdjacentHTML('beforeend',outlets.map(x=>`<option>${esc(x)}</option>`).join(''));$('#outletStrip').innerHTML=summary.map(x=>`<button class="outlet-pill ${outletClass(x.outlet)}" data-outlet="${esc(x.outlet)}"><b>${esc(x.outlet)}</b> · ${x.articles}</button>`).join('');$('#outletDirectory').innerHTML=summary.map(x=>`<button class="outlet-card ${outletClass(x.outlet)}" data-outlet="${esc(x.outlet)}"><strong>${esc(x.outlet)}</strong><span>${x.articles} article titles · ${x.words.toLocaleString()} words</span><em>View articles ↗</em></button>`).join('');bind();applyFilters()}
function bind(){['searchInput','outletSelect','authorInput','dateFrom','dateTo','sortSelect'].forEach(id=>$('#'+id).addEventListener(id==='sortSelect'?'change':'input',()=>{state.page=1;applyFilters()}));$('#resetBtn').onclick=()=>{['searchInput','outletSelect','authorInput','dateFrom','dateTo'].forEach(id=>$('#'+id).value='');state.page=1;applyFilters()};$('#prevBtn').onclick=()=>{state.page--;render();scrollResults()};$('#nextBtn').onclick=()=>{state.page++;render();scrollResults()};const chooseOutlet=e=>{const b=e.target.closest('[data-outlet]');if(b){$('#outletSelect').value=b.dataset.outlet;state.page=1;applyFilters();document.querySelector('.workspace').scrollIntoView({behavior:'smooth',block:'start'})}};$('#outletStrip').onclick=chooseOutlet;$('#outletDirectory').onclick=chooseOutlet;$('#results').onclick=e=>{const b=e.target.closest('[data-id]');if(b)openArticle(b.dataset.id)};$('#aboutBtn').onclick=()=>$('#aboutDialog').showModal();document.querySelectorAll('.research-profile').forEach(b=>b.onclick=()=>$('#aboutDialog').showModal());document.querySelectorAll('.dialog-close').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d)d.close()}))}
function applyFilters(){const q=$('#searchInput').value.toLowerCase().trim(),outlet=$('#outletSelect').value,author=$('#authorInput').value.toLowerCase().trim(),from=$('#dateFrom').value?new Date($('#dateFrom').value):null,to=$('#dateTo').value?new Date($('#dateTo').value+'T23:59:59'):null;state.filtered=state.articles.filter(a=>{const d=parseDate(a.date);return(!q||(a.title+' '+a.author+' '+a.text).toLowerCase().includes(q))&&(!outlet||a.outlet===outlet)&&(!author||a.author.toLowerCase().includes(author))&&(!from||d&&d>=from)&&(!to||d&&d<=to)});const sort=$('#sortSelect').value;state.filtered.sort((a,b)=>sort==='title'?a.title.localeCompare(b.title):sort==='outlet'?a.outlet.localeCompare(b.outlet)||a.title.localeCompare(b.title):(parseDate(a.date)||0)-(parseDate(b.date)||0));if(sort==='date-desc')state.filtered.reverse();render()}
function render(){const pages=Math.max(1,Math.ceil(state.filtered.length/state.pageSize));state.page=Math.min(state.page,pages);const start=(state.page-1)*state.pageSize,items=state.filtered.slice(start,start+state.pageSize);$('#resultsCount').textContent=`${state.filtered.length.toLocaleString()} article records`;$('#activeFilter').textContent=$('#outletSelect').value||'All outlets · Jan–Mar 2026';$('#results').innerHTML=items.length?items.map((a,i)=>`<article class="result ${outletClass(a.outlet)}"><div class="record-index"><b>${esc(a.outlet)}</b>Record ${(start+i+1).toLocaleString()}</div><div><button class="title-button" data-id="${esc(a.id)}">${esc(a.title)}</button><div class="meta"><span>${esc(a.author||'Author not recorded')}</span><span>${esc(displayDate(a.date))}</span><span>${a.word_count.toLocaleString()} words</span></div><p class="snippet">${esc(a.paragraphs.slice(0,2).join(' '))}</p></div><button class="open-record" data-id="${esc(a.id)}" aria-label="Open ${esc(a.title)}">↗</button></article>`).join(''):'<div class="empty"><h3>No matching records</h3><p>Try removing one or more filters.</p></div>';$('#pageInfo').textContent=`Page ${state.page} of ${pages}`;$('#prevBtn').disabled=state.page<=1;$('#nextBtn').disabled=state.page>=pages}
function openArticle(id){const a=state.articles.find(x=>x.id===id);if(!a)return;$('#articleContent').innerHTML=`<p class="eyebrow">${esc(a.outlet)} · corpus record</p><h2>${esc(a.title)}</h2><dl class="article-meta"><div><dt>Author${a.authors.length>1?'s':''}</dt><dd>${esc(a.author||'Not recorded')}</dd></div><div><dt>Publication date</dt><dd>${esc(displayDate(a.date))}</dd></div><div><dt>Corpus length</dt><dd>${a.word_count.toLocaleString()} words</dd></div></dl><div class="article-body">${a.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')}</div>${a.link?`<a class="source-link" href="${esc(a.link)}" target="_blank" rel="noopener noreferrer">Open original source ↗</a>`:''}`;$('#articleDialog').showModal();$('#articleDialog').scrollTop=0}
function scrollResults(){document.querySelector('.results-panel').scrollIntoView({behavior:'smooth',block:'start'})}
async function loadCorpus(){const files=await fetch('data/manifest.json').then(r=>r.json());const parts=await Promise.all(files.map(file=>fetch(`data/${file}`).then(r=>r.arrayBuffer())));const total=parts.reduce((n,p)=>n+p.byteLength,0),joined=new Uint8Array(total);let offset=0;for(const part of parts){joined.set(new Uint8Array(part),offset);offset+=part.byteLength}const stream=new Blob([joined]).stream().pipeThrough(new DecompressionStream('gzip'));return new Response(stream).json()}
Promise.all([
  loadCorpus(),
  fetch('data/summary.json').then(r=>r.json())
]).then(([a,s])=>init(a,s)).catch(()=>{$('#results').innerHTML='<div class="empty"><h3>Corpus records could not be loaded</h3></div>'});
